### ISSUE TITLE
Master does not handle spaces very well

### ISSUE THREAD

**Issue by marvink87** [hSaria/ChromaTerm--#45]
**Describe the bug**
Master does not handle spaces very well

**Environment**
Centos 7

**Configuration File**
```
HIGHLIGHT {\b(flag \[S\]),} {tan} {2}
```

**Additional context**
Using a space in a regex does not work, the following error is looped:
'''
ERROR: Highlight rule not found
'''
This is fixed by using `\s` instead of  ` `. This might be intentional but the error looping is not really nice behaviour.

**Comment by hSaria** [comment]
Thanks for bringing it to my attention. I've just fixed it in the development branch . I'll shortly release version 0.2.3 in the main one.

**Comment by hSaria** [comment]
Oh, and spaces should work fine in a highlight rule (tested it in a few rules), it was just a problem with how a function worked.

**Comment by marvink87** [comment]
Thanks again

**Comment by hSaria** [comment]
Thank **you** for taking the time to submit this.

**Comment by hSaria** [comment]
All done. v0.2.3 is out with this bug fixed.
