### ISSUE TITLE
Syntax Error in Line 2 ~/.chrometermrc

### ISSUE THREAD

**Issue by MKastuv** [hSaria/ChromaTerm--#56]
**Syntax Error in Line 2 ~/.chrometermrc**

There is Syntax Error in Line 2 ~/.chrometermrc when I tried to source it.

```bash
$ source ~/.chromatermrc 
-bash: /bin: Is a directory
-bash: /home/server/.chromatermrc: line 2: syntax error near unexpected token `('
-bash: /home/server/.chromatermrc: line 2: `HIGHLIGHT {(?i)(?<=[\W]|^)(?<!\.)(?:(?P<ip>25[0-5]|(?:2[0-4]|[0-1]?\d)?\d)\.){3}(?P>ip)(?:/\d*)?(?!\.)(?=[\W]|$)} {cyan} {1000}'
```

**Environment**

-   OS: Ubuntu 19.04 Server
-   ChromaTerm-- version: 
```bash
$ ct --version
ct: invalid option -- '-'
ChromaTerm-- v0.3.0
```

**Configuration File**

Issue on:
`HIGHLIGHT {(?i)(?<=[\W]|^)(?<!\.)(?:(?P<ip>25[0-5]|(?:2[0-4]|[0-1]?\d)?\d)\.){3}(?P>ip)(?:/\d*)?(?!\.)(?=[\W]|$)} {cyan} {1000}`

**Comment by hSaria** [comment]
@MKastuv, the configuration file shouldn’t be sourced. By default, ChromaTerm will look for `.chromatermrc` in your home directory. If you wish, you can override the location by using the `-c /path/to/file`

The file contains a list of highlight rules.

**Comment by hSaria** [comment]
If there's anything else I can help with, let me know :)

**Comment by MKastuv** [comment]
~ Thanks hSaria,

I would like to get your help to config ~/.Chometermrc.

- In below figure. I only want to highlight the UPS name i.e. (Matrix UPS not the Host Name).

I have added the following line in ~/.chrometermrc
```ruby
/* CUSTOM HIGHLIGHT */
HIGHLIGHT {(?<=[\W]|^)(.*UPS)(?=[\W]|$)} {yellow} {1000}
```
The logic should be highlight anything before the word UPS. But I could only do it in the entire line after matching the word UPS.
![image](https://user-images.githubusercontent.com/26562660/59613682-f17daf80-90e4-11e9-9bf5-d643ac919f17.png)

**Comment by hSaria** [comment]
You’re actually pretty close.

HIGHLIGHT {(?<=[\W]|^)([\w-]*UPS)(?=[\W]|$)} {yellow} {1000}

The * character is a greedy quantifier, so when you combine it with . (match any character), it will match all it sees. 

“\w” in most RegEx engines is short for “[a-zA-Z0-9_]”, so the alphabet, numbers, and underscores. Notice that it doesn’t match a dash, which is why I gave you a set that includes \w and - instead.

BTW, the bits at the beginning and end of each regex are not mandatory. They’re just backward and forward lookups that will avoid matching the middle of a word.

**Comment by hSaria** [comment]
I can write you a RegEx to highlight the text after “Host Name:“ if you’d like. That way, you don’t need to have UPS in the name.

**Comment by MKastuv** [comment]
Can't believe it just worked. You are so humble and sweet. I hope not to bother you much but if you can write be regex to find Host Name that would be so great. I will post about this project very soon. Such a great tool.

**Comment by hSaria** [comment]
Happy I could be of service. You're too kind with your words. Thank you.

Here's the highlight rule. I've purposefully made the RegEx simple as to not deter you from expanding on it. I've also used a custom color for demonstrative purposes (see `ct -d` for the full list). 

    HIGHLIGHT {(?<=Host Name:)\s+[-\w.]+} {<fad>} {1000}

<img width="590" alt="image" src="https://user-images.githubusercontent.com/34197532/59630034-308b1f80-913c-11e9-8627-d6bcad4f49bb.png">


In terms of the RegEx, it's quite simple:

- `(?<=Host Name:)` is a positive lookbehind, meaning you need to lookbehind the match and find this text. Note that this will not be a part of the match.
- `\s+` to match the spaces (one or more).
- `[-\w.]+` to match one or more of a dash `-`, a word character `a-zA-Z0-9_`, or a dot `.`.

**Comment by MKastuv** [comment]
You genius ! Solved all my problems and described very well :) Is there a way I can follow you on social media to acknowledge your work?

**Comment by hSaria** [comment]
You flatter me too much :)

Nah, I’m quite asocial, but I do appreciate the gesture. I’m thrilled that I‘m able to help. If you’ve got any problems or questions, you know where to find me.
